version: '3'

services:
  db:
    image: mariadb:10.6
    container_name: plag_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"


  web:
    build: .
    container_name: plag_web
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - .:/app
      - static:/app/static  # web 컨테이너의 static 폴더를 공유
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
    command: >
      sh -c "/app/wait-for-it.sh db:3306 && python manage.py makemigrations && python manage.py migrate && python manage.py shell < /app/create_superusers.py && python manage.py collectstatic --noinput && gunicorn plag.wsgi:application --bind 0.0.0.0:8000 --log-level info"


  nginx:
    image: nginx:latest
    container_name: plag_nginx
    volumes:
      - static:/app/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web


volumes:
  db_data:
  static:
