version: '3'

services:
  db:
    image: mariadb:10.6
    container_name: plag_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build: .
    container_name: plag_web
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "plag.wsgi:application"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    container_name: plag_nginx
    volumes:
      - static:/app/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  db_data:
  static:
