version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plag_web
    env_file:
      - .env
    command: gunicorn --bind 0.0.0.0:8000 plag.wsgi:application
    volumes:
      - static:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mariadb:10.6
    container_name: plag_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: plagdb
      MYSQL_USER: plaguser
      MYSQL_PASSWORD: plagpassword
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: plag_nginx
    volumes:
      - static:/app/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static:
  db_data:
