# Generated by Django 5.1.3 on 2024-12-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draw", "0003_drawapplicant_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="drawapplicant",
            name="email_state",
            field=models.BooleanField(default=False),
        ),
    ]
